$baseDir = "d:\Project_Hiver\supportiq\supportiq\src\main\java\com\supportiq\model\intent"
New-Item -ItemType Directory -Force -Path $baseDir | Out-Null

$enums = [ordered]@{
    "DeliverySubCategory" = "DELIVERY_LATE, DELIVERY_DATE, TRACKING_NOT_UPDATED, PACKAGE_MARKED_DELIVERED, DELIVERY_ATTEMPT_FAILED, GENERAL_DELIVERY_QUESTION, COURIER_OR_DRIVER_PROBLEM"
    "OrderSubCategory" = "ORDER_STATUS, CANCEL_ORDER, CHANGE_ORDER, PLACE_ORDER, ORDER_CONFIRMATION, PRE_ORDER, DUPLICATE_ORDER, GENERAL_ORDER_QUESTION"
    "ReturnsSubCategory" = "RETURN_REQUEST, RETURN_STATUS, RETURN_ELIGIBILITY, RETURN_SHIPPING, REFUND_REQUEST, REFUND_PENDING, REFUND_AMOUNT, REFUND_AFTER_CANCELLATION_OR_RETURN"
    "ProductProblemSubCategory" = "DAMAGED_PRODUCT, DEFECTIVE_OR_NOT_WORKING, WRONG_PRODUCT, MISSING_ITEM_OR_COMPONENT, REPLACEMENT_REQUEST, PRODUCT_QUALITY_PROBLEM, OTHER_PRODUCT_PROBLEM"
    "PaymentSubCategory" = "PAYMENT_FAILED, PAYMENT_DECLINED, PAYMENT_VERIFICATION, UNEXPECTED_CHARGE, CHARGE_OR_BILLING_PROBLEM, CARD_CHARGED, GENERAL_PAYMENT_PROBLEM"
    "PrimeMembershipSubCategory" = "GENERAL_PRIME_QUESTION, PRIME_MEMBERSHIP_OR_BENEFITS, PRIME_TRIAL, PRIME_RENEWAL, CANCEL_PRIME, PRIME_MEMBERSHIP_CHARGE, PRIME_DELIVERY_BENEFIT"
    "PrimeVideoSubCategory" = "PRIME_VIDEO_GENERAL, PLAYBACK_OR_TECHNICAL_PROBLEM, CONTENT_AVAILABILITY, MOVIE_OR_SHOW_PURCHASE_OR_RENTAL, DIGITAL_CONTENT_ACCESS, DIGITAL_SUBSCRIPTION_PROBLEM"
    "AmazonDevicesSubCategory" = "ECHO_PROBLEM, ALEXA_PROBLEM, FIRE_TV_OR_FIRE_TV_STICK_PROBLEM, DEVICE_SETUP, DEVICE_CONNECTIVITY, DEVICE_NOT_WORKING, GENERAL_DEVICE_QUESTION"
    "KindleSubCategory" = "KINDLE_OR_READING_GENERAL, KINDLE_OR_EBOOK_ISSUE, KINDLE_BOOK_PURCHASE_OR_PRICING, KINDLE_BOOK_DOWNLOAD, KINDLE_BOOK_ACCESS, KINDLE_DEVICE_PROBLEM"
    "AmazonPaySubCategory" = "AMAZON_PAY_PAYMENT_OR_TRANSACTION, AMAZON_PAY_BALANCE, AMAZON_PAY_CASHBACK_OR_REWARDS, AMAZON_PAY_REFUND, AMAZON_PAY_ACCOUNT, AMAZON_PAY_FRAUD_OR_SUSPICIOUS_TRANSACTION"
    "AccountSubCategory" = "CANNOT_LOGIN, PASSWORD_PROBLEM, ACCOUNT_ACCESS_OR_DETAILS, EMAIL_OR_PHONE_CHANGE, ACCOUNT_LOCKED, ACCOUNT_VERIFICATION, HACKED_OR_COMPROMISED_ACCOUNT"
    "AddressSubCategory" = "ADDRESS_PROBLEM_OR_CHANGE, ADD_OR_REMOVE_ADDRESS, WRONG_DELIVERY_ADDRESS, DELIVERY_LOCATION_OR_SAFE_PLACE, DELIVERY_PREFERENCE"
    "PromotionsSubCategory" = "PROMOTION_OR_DISCOUNT, COUPON_PROBLEM, DISCOUNT_NOT_APPLIED, OFFER_ELIGIBILITY, CASHBACK_OR_PROMOTIONAL_OFFER"
    "GiftCardSubCategory" = "GIFT_CARD_PURCHASE, GIFT_CARD_REDEMPTION, GIFT_CARD_BALANCE, GIFT_CARD_NOT_RECEIVED, GIFT_CARD_NOT_WORKING, GIFT_CARD_CHARGE_OR_PAYMENT"
    "MarketplaceSubCategory" = "THIRD_PARTY_SELLER_PROBLEM, SELLER_COMMUNICATION, SELLER_ORDER_OR_DELIVERY, SELLER_RETURN_OR_REFUND, SELLER_ACCOUNT, SELLER_FRAUD_OR_COUNTERFEIT"
    "ProductInformationSubCategory" = "PRODUCT_PRICE_OR_PRICING, PRODUCT_AVAILABILITY, PRODUCT_INFORMATION, PRODUCT_SPECIFICATION, PRICE_DIFFERENCE_OR_PRICE_CHANGE, GENERAL_PRODUCT_QUESTION"
    "ShippingSubCategory" = "DAMAGED_PACKAGE, OPEN_OR_TAMPERED_PACKAGE, PACKAGING_PROBLEM, SHIPPING_CARRIER_PROBLEM, GENERAL_LOGISTICS_PROBLEM"
    "CustomerServiceSubCategory" = "POOR_CUSTOMER_SERVICE, NO_OR_DELAYED_RESPONSE, REPEATED_CONTACT, UNRESOLVED_ISSUE, GENERAL_SERVICE_COMPLAINT, PRAISE_OR_APPRECIATION"
    "PrivacySubCategory" = "ACCOUNT_SECURITY, SUSPICIOUS_ACTIVITY, UNAUTHORIZED_ACCESS, FRAUD_CONCERN, PERSONAL_INFORMATION_CONCERN, SECURITY_OR_VERIFICATION_PROBLEM"
    "GeneralInformationSubCategory" = "GENERAL_AMAZON_QUESTION, GENERAL_INFORMATION, GENERAL_COMPLAINT, FEEDBACK, PRAISE_OR_APPRECIATION, SOCIAL_OR_CONVERSATIONAL, OTHER_NON_ACTIONABLE_MESSAGE"
}

foreach ($key in $enums.Keys) {
    $vals = $enums[$key]
    $content = "package com.supportiq.model.intent;`n`npublic enum $key implements SubCategory {`n    " + $vals.Replace(", ", ",`n    ") + "`n}"
    Set-Content -Path "$baseDir\$key.java" -Value $content -Encoding UTF8
}

$subCategoryInterface = "package com.supportiq.model.intent;`n`npublic interface SubCategory {`n    String name();`n}"
Set-Content -Path "$baseDir\SubCategory.java" -Value $subCategoryInterface -Encoding UTF8

$mainCategoryEnum = "package com.supportiq.model.intent;`n`npublic enum MainCategory {`n    DELIVERY_AND_TRACKING,`n    ORDER_MANAGEMENT,`n    RETURNS_AND_REFUNDS,`n    PRODUCT_PROBLEM,`n    PAYMENT_AND_BILLING,`n    PRIME_MEMBERSHIP,`n    PRIME_VIDEO_AND_DIGITAL_CONTENT,`n    AMAZON_DEVICES,`n    KINDLE_AND_READING,`n    AMAZON_PAY,`n    ACCOUNT_AND_LOGIN,`n    ADDRESS_AND_DELIVERY_PREFERENCES,`n    PROMOTIONS_AND_DISCOUNTS,`n    GIFT_CARDS,`n    MARKETPLACE_AND_SELLERS,`n    PRODUCT_INFORMATION_AND_PRICING,`n    SHIPPING_PACKAGING_AND_LOGISTICS,`n    CUSTOMER_SERVICE_EXPERIENCE,`n    PRIVACY_AND_SECURITY,`n    GENERAL_INFORMATION_AND_NON_SUPPORT`n}"
Set-Content -Path "$baseDir\MainCategory.java" -Value $mainCategoryEnum -Encoding UTF8
