package com.supportiq.model;

public enum EscalationReason {
    LOW_INTENT_CONFIDENCE,
    NO_HISTORICAL_EVIDENCE,
    LOW_EVIDENCE_RELEVANCE,
    CONFLICTING_EVIDENCE,
    UNSUPPORTED_RESPONSE,
    UNSAFE_RESPONSE,
    PROMPT_INJECTION_RISK,
    AI_SERVICE_FAILURE,
    INVALID_AI_OUTPUT,
    MISSING_REQUIRED_DATA,
    POLICY_SAFETY_FAILURE,
    NONE
}
