package com.supportiq.model;

public enum MainCategory {
    DELIVERY_AND_TRACKING,
    ORDER_MANAGEMENT,
    RETURNS_AND_REFUNDS,
    PRODUCT_PROBLEM,
    PAYMENT_AND_BILLING,
    PRIME_MEMBERSHIP,
    PRIME_VIDEO_AND_DIGITAL_CONTENT,
    AMAZON_DEVICES,
    KINDLE_AND_READING,
    AMAZON_PAY,
    ACCOUNT_AND_LOGIN,
    ADDRESS_AND_DELIVERY_PREFERENCES,
    PROMOTIONS_AND_DISCOUNTS,
    GIFT_CARDS,
    MARKETPLACE_AND_SELLERS,
    PRODUCT_INFORMATION_AND_PRICING,
    SHIPPING_PACKAGING_AND_LOGISTICS,
    CUSTOMER_SERVICE_EXPERIENCE,
    PRIVACY_AND_SECURITY,
    GENERAL_INFORMATION_AND_NON_SUPPORT
}
