import java.io.*;
import java.nio.file.*;
import java.util.*;

public class AnnotateGolden {
    public static void main(String[] args) throws Exception {
        Map<String, String> mapping = new HashMap<>();
        mapping.put("0001", "DELIVERY_AND_TRACKING");
        mapping.put("0002", "DELIVERY_AND_TRACKING");
        mapping.put("0003", "DELIVERY_AND_TRACKING");
        mapping.put("0004", "DELIVERY_AND_TRACKING");
        mapping.put("0005", "DELIVERY_AND_TRACKING");
        mapping.put("0006", "DELIVERY_AND_TRACKING");
        mapping.put("0007", "DELIVERY_AND_TRACKING");
        mapping.put("0008", "DELIVERY_AND_TRACKING");
        mapping.put("0009", "DELIVERY_AND_TRACKING");
        mapping.put("0010", "ORDER_MANAGEMENT");
        mapping.put("0011", "ORDER_MANAGEMENT");
        mapping.put("0012", "ADDRESS_AND_DELIVERY_PREFERENCES");
        mapping.put("0013", "ORDER_MANAGEMENT");
        mapping.put("0014", "ORDER_MANAGEMENT");
        mapping.put("0015", "ORDER_MANAGEMENT");
        mapping.put("0016", "ORDER_MANAGEMENT");
        mapping.put("0017", "ORDER_MANAGEMENT");
        mapping.put("0018", "ORDER_MANAGEMENT");
        mapping.put("0019", "RETURNS_AND_REFUNDS");
        mapping.put("0020", "RETURNS_AND_REFUNDS");
        mapping.put("0021", "RETURNS_AND_REFUNDS");
        mapping.put("0022", "RETURNS_AND_REFUNDS");
        mapping.put("0023", "RETURNS_AND_REFUNDS");
        mapping.put("0024", "RETURNS_AND_REFUNDS");
        mapping.put("0025", "RETURNS_AND_REFUNDS");
        mapping.put("0026", "RETURNS_AND_REFUNDS");
        mapping.put("0027", "RETURNS_AND_REFUNDS");
        mapping.put("0028", "PRODUCT_PROBLEM");
        mapping.put("0029", "PRODUCT_PROBLEM");
        mapping.put("0030", "PRODUCT_PROBLEM");
        mapping.put("0031", "MARKETPLACE_AND_SELLERS");
        mapping.put("0032", "PRODUCT_PROBLEM");
        mapping.put("0033", "PRODUCT_PROBLEM");
        mapping.put("0034", "PRODUCT_PROBLEM");
        mapping.put("0035", "PRODUCT_PROBLEM");
        mapping.put("0036", "PRODUCT_PROBLEM");
        mapping.put("0037", "PAYMENT_AND_BILLING");
        mapping.put("0038", "PAYMENT_AND_BILLING");
        mapping.put("0039", "PAYMENT_AND_BILLING");
        mapping.put("0040", "PAYMENT_AND_BILLING");
        mapping.put("0041", "PAYMENT_AND_BILLING");
        mapping.put("0042", "PAYMENT_AND_BILLING");
        mapping.put("0043", "PAYMENT_AND_BILLING");
        mapping.put("0044", "PAYMENT_AND_BILLING");
        mapping.put("0045", "PAYMENT_AND_BILLING");
        mapping.put("0046", "PRIME_MEMBERSHIP");
        mapping.put("0047", "PRIME_MEMBERSHIP");
        mapping.put("0048", "PRIME_MEMBERSHIP");
        mapping.put("0049", "PRIME_MEMBERSHIP");
        mapping.put("0050", "PRIME_MEMBERSHIP");
        mapping.put("0051", "PRIME_MEMBERSHIP");
        mapping.put("0052", "PRIME_MEMBERSHIP");
        mapping.put("0053", "PRIME_MEMBERSHIP");
        mapping.put("0054", "PRIME_MEMBERSHIP");
        mapping.put("0055", "PRIME_VIDEO_AND_DIGITAL_CONTENT");
        mapping.put("0056", "PRIME_VIDEO_AND_DIGITAL_CONTENT");
        mapping.put("0057", "PRIME_VIDEO_AND_DIGITAL_CONTENT");
        mapping.put("0058", "PRIME_VIDEO_AND_DIGITAL_CONTENT");
        mapping.put("0059", "PRIME_VIDEO_AND_DIGITAL_CONTENT");
        mapping.put("0060", "PRIME_VIDEO_AND_DIGITAL_CONTENT");
        mapping.put("0061", "PRIME_VIDEO_AND_DIGITAL_CONTENT");
        mapping.put("0062", "PRIME_VIDEO_AND_DIGITAL_CONTENT");
        mapping.put("0063", "PRIME_VIDEO_AND_DIGITAL_CONTENT");
        mapping.put("0064", "AMAZON_DEVICES");
        mapping.put("0065", "AMAZON_DEVICES");
        mapping.put("0066", "AMAZON_DEVICES");
        mapping.put("0067", "AMAZON_DEVICES");
        mapping.put("0068", "KINDLE_AND_READING");
        mapping.put("0069", "AMAZON_DEVICES");
        mapping.put("0070", "AMAZON_DEVICES");
        mapping.put("0071", "AMAZON_DEVICES");
        mapping.put("0072", "AMAZON_DEVICES");
        mapping.put("0073", "KINDLE_AND_READING");
        mapping.put("0074", "KINDLE_AND_READING");
        mapping.put("0075", "KINDLE_AND_READING");
        mapping.put("0076", "KINDLE_AND_READING");
        mapping.put("0077", "KINDLE_AND_READING");
        mapping.put("0078", "KINDLE_AND_READING");
        mapping.put("0079", "KINDLE_AND_READING");
        mapping.put("0080", "KINDLE_AND_READING");
        mapping.put("0081", "KINDLE_AND_READING");
        mapping.put("0082", "AMAZON_PAY");
        mapping.put("0083", "AMAZON_PAY");
        mapping.put("0084", "AMAZON_PAY");
        mapping.put("0085", "AMAZON_PAY");
        mapping.put("0086", "AMAZON_PAY");
        mapping.put("0087", "AMAZON_PAY");
        mapping.put("0088", "AMAZON_PAY");
        mapping.put("0089", "AMAZON_PAY");
        mapping.put("0090", "AMAZON_PAY");
        mapping.put("0091", "ACCOUNT_AND_LOGIN");
        mapping.put("0092", "ACCOUNT_AND_LOGIN");
        mapping.put("0093", "ACCOUNT_AND_LOGIN");
        mapping.put("0094", "ACCOUNT_AND_LOGIN");
        mapping.put("0095", "ACCOUNT_AND_LOGIN");
        mapping.put("0096", "ACCOUNT_AND_LOGIN");
        mapping.put("0097", "ACCOUNT_AND_LOGIN");
        mapping.put("0098", "ACCOUNT_AND_LOGIN");
        mapping.put("0099", "ACCOUNT_AND_LOGIN");
        mapping.put("0100", "ADDRESS_AND_DELIVERY_PREFERENCES");
        mapping.put("0101", "ADDRESS_AND_DELIVERY_PREFERENCES");
        mapping.put("0102", "ADDRESS_AND_DELIVERY_PREFERENCES");
        mapping.put("0103", "ADDRESS_AND_DELIVERY_PREFERENCES");
        mapping.put("0104", "ADDRESS_AND_DELIVERY_PREFERENCES");
        mapping.put("0105", "ADDRESS_AND_DELIVERY_PREFERENCES");
        mapping.put("0106", "ADDRESS_AND_DELIVERY_PREFERENCES");
        mapping.put("0107", "ADDRESS_AND_DELIVERY_PREFERENCES");
        mapping.put("0108", "ADDRESS_AND_DELIVERY_PREFERENCES");
        mapping.put("0109", "PROMOTIONS_AND_DISCOUNTS");
        mapping.put("0110", "PROMOTIONS_AND_DISCOUNTS");
        mapping.put("0111", "PROMOTIONS_AND_DISCOUNTS");
        mapping.put("0112", "PROMOTIONS_AND_DISCOUNTS");
        mapping.put("0113", "PROMOTIONS_AND_DISCOUNTS");
        mapping.put("0114", "PROMOTIONS_AND_DISCOUNTS");
        mapping.put("0115", "PROMOTIONS_AND_DISCOUNTS");
        mapping.put("0116", "PROMOTIONS_AND_DISCOUNTS");
        mapping.put("0117", "PROMOTIONS_AND_DISCOUNTS");
        mapping.put("0118", "GIFT_CARDS");
        mapping.put("0119", "GIFT_CARDS");
        mapping.put("0120", "GIFT_CARDS");
        mapping.put("0121", "GIFT_CARDS");
        mapping.put("0122", "GIFT_CARDS");
        mapping.put("0123", "GIFT_CARDS");
        mapping.put("0124", "GIFT_CARDS");
        mapping.put("0125", "GIFT_CARDS");
        mapping.put("0126", "GIFT_CARDS");
        mapping.put("0127", "MARKETPLACE_AND_SELLERS");
        mapping.put("0128", "MARKETPLACE_AND_SELLERS");
        mapping.put("0129", "MARKETPLACE_AND_SELLERS");
        mapping.put("0130", "MARKETPLACE_AND_SELLERS");
        mapping.put("0131", "MARKETPLACE_AND_SELLERS");
        mapping.put("0132", "MARKETPLACE_AND_SELLERS");
        mapping.put("0133", "MARKETPLACE_AND_SELLERS");
        mapping.put("0134", "MARKETPLACE_AND_SELLERS");
        mapping.put("0135", "MARKETPLACE_AND_SELLERS");
        mapping.put("0136", "PRODUCT_INFORMATION_AND_PRICING");
        mapping.put("0137", "PRODUCT_INFORMATION_AND_PRICING");
        mapping.put("0138", "PRODUCT_INFORMATION_AND_PRICING");
        mapping.put("0139", "PRODUCT_INFORMATION_AND_PRICING");
        mapping.put("0140", "PRODUCT_INFORMATION_AND_PRICING");
        mapping.put("0141", "PRODUCT_INFORMATION_AND_PRICING");
        mapping.put("0142", "PRODUCT_INFORMATION_AND_PRICING");
        mapping.put("0143", "PRODUCT_INFORMATION_AND_PRICING");
        mapping.put("0144", "PRODUCT_INFORMATION_AND_PRICING");
        mapping.put("0145", "SHIPPING_PACKAGING_AND_LOGISTICS");
        mapping.put("0146", "SHIPPING_PACKAGING_AND_LOGISTICS");
        mapping.put("0147", "SHIPPING_PACKAGING_AND_LOGISTICS");
        mapping.put("0148", "SHIPPING_PACKAGING_AND_LOGISTICS");
        mapping.put("0149", "SHIPPING_PACKAGING_AND_LOGISTICS");
        mapping.put("0150", "SHIPPING_PACKAGING_AND_LOGISTICS");
        mapping.put("0151", "SHIPPING_PACKAGING_AND_LOGISTICS");
        mapping.put("0152", "SHIPPING_PACKAGING_AND_LOGISTICS");
        mapping.put("0153", "SHIPPING_PACKAGING_AND_LOGISTICS");
        mapping.put("0154", "CUSTOMER_SERVICE_EXPERIENCE");
        mapping.put("0155", "CUSTOMER_SERVICE_EXPERIENCE");
        mapping.put("0156", "CUSTOMER_SERVICE_EXPERIENCE");
        mapping.put("0157", "CUSTOMER_SERVICE_EXPERIENCE");
        mapping.put("0158", "CUSTOMER_SERVICE_EXPERIENCE");
        mapping.put("0159", "CUSTOMER_SERVICE_EXPERIENCE");
        mapping.put("0160", "CUSTOMER_SERVICE_EXPERIENCE");
        mapping.put("0161", "CUSTOMER_SERVICE_EXPERIENCE");
        mapping.put("0162", "CUSTOMER_SERVICE_EXPERIENCE");
        mapping.put("0163", "PRIVACY_AND_SECURITY");
        mapping.put("0164", "PRIVACY_AND_SECURITY");
        mapping.put("0165", "PRIVACY_AND_SECURITY");
        mapping.put("0166", "PRIVACY_AND_SECURITY");
        mapping.put("0167", "PRIVACY_AND_SECURITY");
        mapping.put("0168", "PRIVACY_AND_SECURITY");
        mapping.put("0169", "PRIVACY_AND_SECURITY");
        mapping.put("0170", "PRIVACY_AND_SECURITY");
        mapping.put("0171", "PRIVACY_AND_SECURITY");
        mapping.put("0172", "GENERAL_INFORMATION_AND_NON_SUPPORT");
        mapping.put("0173", "GENERAL_INFORMATION_AND_NON_SUPPORT");
        mapping.put("0174", "GENERAL_INFORMATION_AND_NON_SUPPORT");
        mapping.put("0175", "GENERAL_INFORMATION_AND_NON_SUPPORT");
        mapping.put("0176", "GENERAL_INFORMATION_AND_NON_SUPPORT");
        mapping.put("0177", "GENERAL_INFORMATION_AND_NON_SUPPORT");
        mapping.put("0178", "GENERAL_INFORMATION_AND_NON_SUPPORT");
        mapping.put("0179", "GENERAL_INFORMATION_AND_NON_SUPPORT");
        mapping.put("0180", "GENERAL_INFORMATION_AND_NON_SUPPORT");
        mapping.put("0181", "DELIVERY_AND_TRACKING");
        mapping.put("0182", "ORDER_MANAGEMENT");
        mapping.put("0183", "GENERAL_INFORMATION_AND_NON_SUPPORT");
        mapping.put("0184", "PAYMENT_AND_BILLING");
        mapping.put("0185", "SHIPPING_PACKAGING_AND_LOGISTICS");
        mapping.put("0186", "RETURNS_AND_REFUNDS");
        mapping.put("0187", "GENERAL_INFORMATION_AND_NON_SUPPORT");
        mapping.put("0188", "ORDER_MANAGEMENT");
        mapping.put("0189", "PAYMENT_AND_BILLING");
        mapping.put("0190", "PRIME_MEMBERSHIP");
        mapping.put("0191", "PRIVACY_AND_SECURITY");
        mapping.put("0192", "GIFT_CARDS");
        mapping.put("0193", "PRODUCT_INFORMATION_AND_PRICING");
        
        Path path = Paths.get("d:/Project_Hiver/supportiq/supportiq/data/evaluation/golden_dataset.jsonl");
        List<String> lines = Files.readAllLines(path);
        List<String> outLines = new ArrayList<>();
        
        for (String line : lines) {
            if (line.trim().isEmpty()) continue;
            for (Map.Entry<String, String> entry : mapping.entrySet()) {
                String idPart = "\"id\": \"" + entry.getKey() + "\"";
                if (line.contains(idPart)) {
                    // Quick and dirty string replace to insert expectedIntent
                    if (!line.contains("\"expectedIntent\"")) {
                        line = line.replace("\"pair\": {", "\"pair\": {\"expectedIntent\": \"" + entry.getValue() + "\", ");
                    } else {
                        // Already has it, replace it
                        line = line.replaceAll("\"expectedIntent\": \"[^\"]+\"", "\"expectedIntent\": \"" + entry.getValue() + "\"");
                    }
                    break;
                }
            }
            outLines.add(line);
        }
        
        Files.write(path, outLines);
        System.out.println("Done");
    }
}
